WITH SRC AS (
    SELECT 
        DISTINCT INSURANCE_TYPE
    FROM 
        {{ ref('snapshot_staging_contract') }}
)

SELECT
    MD5(TRIM(INSURANCE_TYPE)) AS INSURANCE_TYPE_KEY
    , INSURANCE_TYPE
FROM SRC
WHERE
    DBT_VALID_TO = '9999-12-31'