WITH SRC AS (
    SELECT 
        DISTINCT PAYMENT_PLAN
    FROM 
        {{ ref('snapshot_staging_contract') }}
)
SELECT
    MD5(TRIM(PAYMENT_PLAN)) AS PAYMENT_PLAN_KEY
    , PAYMENT_PLAN
FROM SRC
WHERE
    DBT_VALID_TO = '9999-12-31'