
version: 3

models:
  - name: staging_claim
  - name: staging_client
  - name: staging_contract  

sources:
  - name: seed
    database: target  
    schema: public_raw  
    tables:
      - name: claim
      - name: client
      - name: contract
