
version: 3

models:
  - name: staging_claim
  - name: staging_client
  - name: staging_contract
  - name: dim_claim_status
  - name: dim_claim_type
  - name: dim_insurance_type
  - name: dim_payment_plan
  - name: fact_claim
  - name: fact_contract
  - name: client_count_claim_sum_amount
  - name: client_sum_revenue


sources:
  - name: seed
    database: target  
    schema: public_raw  
    tables:
      - name: claim
      - name: client
      - name: contract
