services :
    postgres_target:
        image: postgres:latest
        ports:
            - ${PORT}:${PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
              test:
                [
                  "CMD",
                  "pg_isready",
                  "-d",
                  "postgres",
                  "-h",
                  "${POSTGRES_DB}", 
                  "-p ${PORT}",
                  "-U postgres",
                ]
              interval: 5s
              timeout: 5s
              retries: 5
