services:
  postgres_target_training:
    image: postgres:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-h",
          "localhost",
          "-p",
          "${PORT}",
          "-U",
          "${POSTGRES_USER}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt_python:
    build:
      context: .
      dockerfile: Dockerfile
    # --- ADDED PORTS FOR DBT DOCS ---
    ports:
      - "8080:8080" 
    # --------------------------------
    volumes:
      - .:/usr/app
    tty: true           # Keeps the container running for interactive use
    stdin_open: true    # Allows you to attach to the shell
    environment:
      POSTGRES_HOST: postgres_target_training
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${PORT}
      DBT_PROFILES_DIR: /usr/app
    depends_on:
      postgres_target_training:
        condition: service_healthy
    command: >
      bash -c "dbt docs generate && dbt docs serve --host 0.0.0.0 --port 8080"
volumes:
  postgres_data: