
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_showroom'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_showroom'
seeds:
  dbt_showroom: 
    schema: raw
    delimiter: "," # default delimiter for seeds in dbt_showroom project will be ","
    claim:
      delimiter: ";"
    contract:
      delimiter: ";"
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["dbt_showroom/models"]
analysis-paths: ["dbt_showroom/analyses"]
test-paths: ["dbt_showroom/tests"]
seed-paths: ["dbt_showroom/seeds"]
macro-paths: ["dbt_showroom/macros"]
snapshot-paths: ["dbt_showroom/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


snapshots:
  dbt_showroom:
    +schema: schnapshot
    +unique_key: HASH_PK
    +strategy: check      
    +check_cols:
      - HASH_DIFF
    +dbt_valid_to_current: "DATE('9999-12-31')"
    +snapshot_meta_column_names:
      dbt_valid_from: VALID_FROM
      dbt_valid_to: VALID_TO
    +hard_deletes: 'invalidate'


models:
  dbt_showroom:
    staging:
      +materialized: incremental
      +schema: staging
      +on_schema_change: append_new_columns
      +tags: 
        - "staging"
        - "bronze"
    mart:
      +materialized: table
      +schema: mart
      +tags:
        - "mart"
        - "gold"
      dim:
        +tags:
          - "dimension"
      fact:
        +tags:
          - "fact"
      views:
        +materialized: view
        +tags:
          - "flatmart"