
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_showroom'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_showroom'
seeds:
  dbt_showroom: 
    schema: raw
    delimiter: "," # default delimiter for seeds in dbt_showroom project will be ","
    claim:
      delimiter: ";"
    contract:
      delimiter: ";"
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["dbt_showroom/models"]
analysis-paths: ["dbt_showroom/analyses"]
test-paths: ["dbt_showroom/tests"]
seed-paths: ["dbt_showroom/seeds"]
macro-paths: ["dbt_showroom/macros"]
snapshot-paths: ["dbt_showroom/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_showroom:
