
version: 2

models:
  - name: client_sum_revenue
    description: "sums up revenue per client"
    columns:
      - name: client_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: revenue_per_client
        description: "sums up the monthly premium per client id"
        data_test:
          - <= 0
          - not_null